# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: itinerary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'itinerary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fitinerary.proto\x12\rgrpc_services\"@\n\x10ItineraryRequest\x12\x16\n\x0estart_location\x18\x01 \x01(\t\x12\x14\n\x0c\x65nd_location\x18\x02 \x01(\t\"\"\n\x11ItineraryResponse\x12\r\n\x05steps\x18\x01 \x03(\t2e\n\x10ItineraryService\x12Q\n\x0cGetItinerary\x12\x1f.grpc_services.ItineraryRequest\x1a .grpc_services.ItineraryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itinerary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITINERARYREQUEST']._serialized_start=34
  _globals['_ITINERARYREQUEST']._serialized_end=98
  _globals['_ITINERARYRESPONSE']._serialized_start=100
  _globals['_ITINERARYRESPONSE']._serialized_end=134
  _globals['_ITINERARYSERVICE']._serialized_start=136
  _globals['_ITINERARYSERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
