# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: traffic.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'traffic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtraffic.proto\x12\rgrpc_services\"\"\n\x0eTrafficRequest\x12\x10\n\x08location\x18\x01 \x01(\t\";\n\x0fTrafficResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x18\n\x10\x63ongestion_level\x18\x02 \x01(\x05\x32\x63\n\x0eTrafficService\x12Q\n\x10GetTrafficStatus\x12\x1d.grpc_services.TrafficRequest\x1a\x1e.grpc_services.TrafficResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traffic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAFFICREQUEST']._serialized_start=32
  _globals['_TRAFFICREQUEST']._serialized_end=66
  _globals['_TRAFFICRESPONSE']._serialized_start=68
  _globals['_TRAFFICRESPONSE']._serialized_end=127
  _globals['_TRAFFICSERVICE']._serialized_start=129
  _globals['_TRAFFICSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
