# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_services import transport_pb2 as transport__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBestItinerary = channel.unary_unary(
                '/TransportService/GetBestItinerary',
                request_serializer=transport__pb2.ItineraryRequest.SerializeToString,
                response_deserializer=transport__pb2.ItineraryResponse.FromString,
                _registered_method=True)
        self.PredictTraffic = channel.unary_unary(
                '/TransportService/PredictTraffic',
                request_serializer=transport__pb2.TrafficRequest.SerializeToString,
                response_deserializer=transport__pb2.TrafficResponse.FromString,
                _registered_method=True)
        self.ListTransportsAvailable = channel.unary_unary(
                '/TransportService/ListTransportsAvailable',
                request_serializer=transport__pb2.TransportRequest.SerializeToString,
                response_deserializer=transport__pb2.TransportList.FromString,
                _registered_method=True)


class TransportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBestItinerary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictTraffic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTransportsAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBestItinerary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestItinerary,
                    request_deserializer=transport__pb2.ItineraryRequest.FromString,
                    response_serializer=transport__pb2.ItineraryResponse.SerializeToString,
            ),
            'PredictTraffic': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTraffic,
                    request_deserializer=transport__pb2.TrafficRequest.FromString,
                    response_serializer=transport__pb2.TrafficResponse.SerializeToString,
            ),
            'ListTransportsAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTransportsAvailable,
                    request_deserializer=transport__pb2.TransportRequest.FromString,
                    response_serializer=transport__pb2.TransportList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TransportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBestItinerary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransportService/GetBestItinerary',
            transport__pb2.ItineraryRequest.SerializeToString,
            transport__pb2.ItineraryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictTraffic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransportService/PredictTraffic',
            transport__pb2.TrafficRequest.SerializeToString,
            transport__pb2.TrafficResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTransportsAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransportService/ListTransportsAvailable',
            transport__pb2.TransportRequest.SerializeToString,
            transport__pb2.TransportList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
