# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\"7\n\x10ItineraryRequest\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\"R\n\x11ItineraryResponse\x12\r\n\x05route\x18\x01 \x01(\t\x12\x16\n\x0etransport_type\x18\x02 \x01(\t\x12\x16\n\x0e\x65stimated_time\x18\x03 \x01(\x02\"G\n\x0eTrafficRequest\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\t\" \n\x0fTrafficResponse\x12\r\n\x05level\x18\x01 \x01(\t\" \n\x10TransportRequest\x12\x0c\n\x04zone\x18\x01 \x01(\t\"#\n\rTransportList\x12\x12\n\ntransports\x18\x01 \x03(\t2\xc0\x01\n\x10TransportService\x12\x39\n\x10GetBestItinerary\x12\x11.ItineraryRequest\x1a\x12.ItineraryResponse\x12\x33\n\x0ePredictTraffic\x12\x0f.TrafficRequest\x1a\x10.TrafficResponse\x12<\n\x17ListTransportsAvailable\x12\x11.TransportRequest\x1a\x0e.TransportListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITINERARYREQUEST']._serialized_start=19
  _globals['_ITINERARYREQUEST']._serialized_end=74
  _globals['_ITINERARYRESPONSE']._serialized_start=76
  _globals['_ITINERARYRESPONSE']._serialized_end=158
  _globals['_TRAFFICREQUEST']._serialized_start=160
  _globals['_TRAFFICREQUEST']._serialized_end=231
  _globals['_TRAFFICRESPONSE']._serialized_start=233
  _globals['_TRAFFICRESPONSE']._serialized_end=265
  _globals['_TRANSPORTREQUEST']._serialized_start=267
  _globals['_TRANSPORTREQUEST']._serialized_end=299
  _globals['_TRANSPORTLIST']._serialized_start=301
  _globals['_TRANSPORTLIST']._serialized_end=336
  _globals['_TRANSPORTSERVICE']._serialized_start=339
  _globals['_TRANSPORTSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
