# Generated by Django 5.2.1 on 2025-05-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("agent_type", models.CharField(max_length=20)),
                ("from_zone", models.CharField(max_length=100)),
                ("to_zone", models.CharField(max_length=100)),
            ],
        ),
    ]
