syntax = "proto3";

package transport;

import "google/protobuf/empty.proto";

message Vehicle {
  string id = 1;
  double lat = 2;
  double lng = 3;
}

service TransportService {
  rpc GetRoute (RouteRequest) returns (RouteResponse);
  rpc StreamVehicles (google.protobuf.Empty) returns (stream Vehicle);
}


// Messages
message RouteRequest {
  double start_lat = 1;
  double start_lng = 2;
  double end_lat = 3;
  double end_lng = 4;
}

message RouteResponse {
  repeated string path = 1;
  string transport_mode = 2;
  double distance = 3;
}

message VehiclePosition {
  string vehicle_id = 1;
  double lat = 2;
  double lng = 3;
}
